# Generated by Django 4.2.4 on 2023-08-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'отклик', 'verbose_name_plural': 'отклики'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='publication',
        ),
    ]
