# Generated by Django 4.2.4 on 2023-08-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_remove_post_category_delete_postcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
